version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: db_repuestos_equipob
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: repuestos_db
    ports:
      - "3306:3306"