version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mercedesADB
    ports:
      - "3307:3306"
    networks:
      - app-network

  app:
    build: .
    container_name: spring-app
    depends_on:
      - mysql
    networks:
      - app-network

networks:
  app-network: